package com.example.isthisangela.miniproj1;

/**
 * Created by isthisangela on 2/9/18.
 */

public class Members {
    Integer[] pics = {
            R.drawable.aayushtyagi,
            R.drawable.abhinavkoppu,
            R.drawable.adityayadav,
            R.drawable.akkshaykhoslaa,
            R.drawable.amyshen,
            R.drawable.aneeshjindal,
            R.drawable.angeladong,
            R.drawable.ayushkumar,
            R.drawable.candiceye,
            R.drawable.carolwang,
            R.drawable.codyhsieh,
            R.drawable.danielandrews,
            R.drawable.erickong,
            R.drawable.ethanwong,
            R.drawable.fangshuo,
            R.drawable.japjotsingh,
            R.drawable.jeffreyzhang,
            R.drawable.joeyhejna,
            R.drawable.juliedeng,
            R.drawable.justinkim,
            R.drawable.kadendippe,
            R.drawable.kanyesthaker,
            R.drawable.krishnanrajiyah,
            R.drawable.leonkwak,
            R.drawable.leviwalsh,
            R.drawable.louiemcconnell,
            R.drawable.maxmiranda,
            R.drawable.mohitkatyal,
            R.drawable.mudabbirkhan,
            R.drawable.natashawong,
            R.drawable.nikhararora,
            R.drawable.noahpepper,
            R.drawable.radhikadhomse,
            R.drawable.sahillamba,
            R.drawable.samanvirai,
            R.drawable.sarahtang,
            R.drawable.shariewang,
            R.drawable.shivkushwah,
            R.drawable.shreyareddy,
            R.drawable.shubhamgupta,
            R.drawable.srujaykorlakunta,
            R.drawable.stephenjayakar,
            R.drawable.sumukhshivakumar,
            R.drawable.suyashgupta,
            R.drawable.tigerchen,
            R.drawable.victorsun,
            R.drawable.vidyaravikumar,
            R.drawable.vineethyeevani,
            R.drawable.wilburshi,
            R.drawable.williamlu,
            R.drawable.willoakley,
            R.drawable.xinyichen,
            R.drawable.younglin,
            R.drawable.zachgovani
    }
    String[] names = {
            "Aayush Tyagi",
            "Abhinav Koppu",
            "Aditya Yadav",
            "Akkshay Khoslaa",
            "Amy Shen",
            "Aneesh Jindal",
            "Angela Dong",
            "Ayush Kumar",
            "Candice Ye",
            "Carol Wang",
            "Cody Hsieh",
            "Daniel Andrews",
            "Eric Kong",
            "Ethan Wong",
            "Fang Shuo",
            "Japjot Singh",
            "Jeffrey Zhang",
            "Joey Hejna",
            "Julie Deng",
            "Justin Kim",
            "Kaden Dippe",
            "Kanyes Thaker",
            "Krishna Rajiyah",
            "Leon Kwak",
            "Levi Walsh",
            "Louie McConnell",
            "Max Miranda",
            "Mohit Katyal",
            "Mudabbir Khan",
            "Natasha Wong",
            "Nikhar Arora",
            "Noah Pepper",
            "Radhika Dhomse",
            "Sahil Lamba",
            "Saman Virai",
            "Sarah Tang",
            "Sharie Wang",
            "Shiv Kushwah",
            "Shreya Reddy",
            "Shubham Gupta",
            "Srujay Korlakunta",
            "Stephen Jayakar",
            "Sumukh Shivakumar",
            "Suyash Gupta",
            "Tiger Chen",
            "Victor Sun",
            "Vidya Ravikumar",
            "Vineeth Yeevani",
            "Wilbur Shi",
            "William Lu",
            "Will Oakley",
            "Xin Yi Chen",
            "Young Lin",
            "Zach Govani"
    }
}
